// Archivo: scripts/format_l1_modular.cjs
const fs = require('fs');
const path = require('path');

const targetPath = path.join(__dirname, '../backend/stitch/widgets/booking/booking_l1_turnero.html');

const lines = [
  '<!-- Archivo: backend/stitch/widgets/booking/booking_l1_turnero.html -->',
  '<div id="smart-turnero-widget-{{WIDGET_ID}}" data-widget-id="{{WIDGET_ID}}" data-biz-name="{{BUSINESS_NAME}}" data-wa="{{WHATSAPP_NUMBER}}" data-open="09:00" data-close="13:00" data-split="true" data-open2="17:00" data-close2="21:00" data-interval="30" data-days="14" data-workdays="1,2,3,4,5,6" data-block-holidays="true" data-template="¡Hola! Quiero confirmar mi reserva en {{comercio}}:\\n- 👤 Nombre: {{cliente}}\\n- 📅 Día: {{fecha}}\\n- ⏰ Hora: {{hora}}\\n- 📞 Tel: {{telefono}}\\n¿Me confirman disponibilidad?" class="w-full max-w-[440px] mx-auto bg-zinc-900/95 text-zinc-100 backdrop-blur-xl rounded-[2rem] border border-zinc-800 p-6 sm:p-7 shadow-2xl relative overflow-hidden font-sans transition-all duration-300 box-border">',
  '  <div class="text-center mb-6">',
  '    <h3 class="text-xl sm:text-2xl font-bold mb-1 leading-tight text-white" id="biz-title-{{WIDGET_ID}}">Reservar en {{BUSINESS_NAME}}</h3>',
  '    <p class="text-xs sm:text-sm text-zinc-400" id="turnero-subtitle-{{WIDGET_ID}}">Paso 1: Selecciona fecha y hora</p>',
  '    <div class="flex items-center justify-center gap-2 mt-4">',
  '      <div id="step-dot-1-{{WIDGET_ID}}" class="w-7 h-7 rounded-full bg-blue-600 text-white font-bold text-xs flex items-center justify-center shadow-lg shadow-blue-500/20 transition-all">1</div>',
  '      <div class="w-8 sm:w-11 h-1 bg-zinc-800 rounded-full overflow-hidden"><div id="step-bar-1-{{WIDGET_ID}}" class="h-full bg-blue-600 w-0 transition-all duration-300"></div></div>',
  '      <div id="step-dot-2-{{WIDGET_ID}}" class="w-7 h-7 rounded-full bg-zinc-800 text-zinc-400 font-bold text-xs flex items-center justify-center transition-all">2</div>',
  '      <div class="w-8 sm:w-11 h-1 bg-zinc-800 rounded-full overflow-hidden"><div id="step-bar-2-{{WIDGET_ID}}" class="h-full bg-blue-600 w-0 transition-all duration-300"></div></div>',
  '      <div id="step-dot-3-{{WIDGET_ID}}" class="w-7 h-7 rounded-full bg-zinc-800 text-zinc-400 font-bold text-xs flex items-center justify-center transition-all">3</div>',
  '    </div>',
  '  </div>',
  '  <div class="grid w-full overflow-hidden">',
  '    <div id="step-1-{{WIDGET_ID}}" class="[grid-area:1/1] w-full min-w-0 box-border transition-all duration-500 ease-in-out opacity-100 transform translate-x-0">',
  '      <div class="mb-5 w-full">',
  '        <div class="flex items-center justify-between mb-2"><label class="block text-xs sm:text-sm font-medium text-zinc-300">Selecciona un día:</label><div class="flex items-center gap-1.5"><button id="day-prev-{{WIDGET_ID}}" class="w-7 h-7 rounded-lg bg-zinc-800 hover:bg-zinc-700 disabled:opacity-25 disabled:cursor-not-allowed text-zinc-300 flex items-center justify-center text-xs transition-all">←</button><button id="day-next-{{WIDGET_ID}}" class="w-7 h-7 rounded-lg bg-zinc-800 hover:bg-zinc-700 disabled:opacity-25 disabled:cursor-not-allowed text-zinc-300 flex items-center justify-center text-xs transition-all">→</button></div></div>',
  '        <div class="grid grid-cols-4 gap-2 w-full" id="day-selector-{{WIDGET_ID}}"></div>',
  '      </div>',
  '      <div class="w-full"><label class="block text-xs sm:text-sm font-medium mb-2 text-zinc-300">Horarios disponibles:</label><div class="grid grid-cols-3 sm:grid-cols-4 gap-2.5 w-full max-h-64 sm:max-h-72 overflow-y-auto pr-1 hide-scrollbar" id="time-selector-{{WIDGET_ID}}"></div></div>',
  '      <button id="btn-next-1-{{WIDGET_ID}}" disabled class="mt-6 w-full py-4 rounded-xl font-bold text-sm sm:text-base bg-blue-600 text-white hover:bg-blue-500 transition-all shadow-lg shadow-blue-600/20 disabled:bg-zinc-800 disabled:text-zinc-500 disabled:opacity-40 disabled:cursor-not-allowed">Continuar</button>',
  '    </div>',
  '    <div id="step-2-{{WIDGET_ID}}" class="[grid-area:1/1] w-full min-w-0 box-border transition-all duration-500 ease-in-out opacity-0 pointer-events-none transform translate-x-full space-y-4 pt-1">',
  '      <div><label class="block text-xs sm:text-sm font-medium mb-1.5 text-zinc-300">Teléfono / WhatsApp</label><input type="tel" inputmode="numeric" autocomplete="tel" id="input-phone-{{WIDGET_ID}}" maxlength="15" placeholder="Ej. 3811234567" class="w-full bg-zinc-950/70 border border-zinc-700/70 rounded-xl px-4 py-3.5 text-sm text-zinc-100 placeholder:text-zinc-500 outline-none focus:ring-2 focus:ring-blue-500 transition-all"></div>',
  '      <div class="grid grid-cols-2 gap-2.5">',
  '        <div><label class="block text-xs sm:text-sm font-medium mb-1.5 text-zinc-300">Nombre</label><input type="text" autocapitalize="words" autocomplete="given-name" id="input-fname-{{WIDGET_ID}}" placeholder="Ej. Juan" class="w-full bg-zinc-950/70 border border-zinc-700/70 rounded-xl px-3.5 py-3.5 text-sm text-zinc-100 placeholder:text-zinc-500 outline-none focus:ring-2 focus:ring-blue-500 transition-all"></div>',
  '        <div><label class="block text-xs sm:text-sm font-medium mb-1.5 text-zinc-300">Apellido</label><input type="text" autocapitalize="words" autocomplete="family-name" id="input-lname-{{WIDGET_ID}}" placeholder="Ej. Pérez" class="w-full bg-zinc-950/70 border border-zinc-700/70 rounded-xl px-3.5 py-3.5 text-sm text-zinc-100 placeholder:text-zinc-500 outline-none focus:ring-2 focus:ring-blue-500 transition-all"></div>',
  '      </div>',
  '      <div id="step-2-error-{{WIDGET_ID}}" class="text-xs text-rose-400 font-medium hidden"></div>',
  '      <div class="flex gap-2.5 pt-2 mt-6"><button id="btn-back-2-{{WIDGET_ID}}" class="w-1/3 py-4 rounded-xl font-bold bg-zinc-800 hover:bg-zinc-700 text-zinc-300 border border-zinc-700/50 transition-colors text-sm">Volver</button><button id="btn-next-2-{{WIDGET_ID}}" class="w-2/3 py-4 rounded-xl font-bold bg-blue-600 text-white hover:bg-blue-500 transition-all shadow-lg shadow-blue-600/20 text-sm">Revisar</button></div>',
  '    </div>',
  '    <div id="step-3-{{WIDGET_ID}}" class="[grid-area:1/1] w-full min-w-0 box-border transition-all duration-500 ease-in-out opacity-0 pointer-events-none transform translate-x-full flex flex-col justify-between">',
  '      <div class="bg-zinc-950/60 rounded-2xl p-5 sm:p-6 border border-zinc-800/80 w-full min-w-0 box-border">',
  '        <h4 class="font-bold text-base sm:text-lg mb-4 text-center text-white">Resumen de tu reserva</h4>',
  '        <ul class="space-y-3 text-xs sm:text-sm w-full min-w-0">',
  '          <li class="flex justify-between items-start gap-3 border-b border-zinc-800/80 pb-2.5 min-w-0"><span class="text-zinc-400 flex-shrink-0">Nombre:</span><span class="font-semibold text-zinc-100 text-right break-words min-w-0" id="summary-name-{{WIDGET_ID}}">-</span></li>',
  '          <li class="flex justify-between items-start gap-3 border-b border-zinc-800/80 pb-2.5 min-w-0"><span class="text-zinc-400 flex-shrink-0">Día:</span><span class="font-semibold text-zinc-100 text-right break-words min-w-0" id="summary-day-{{WIDGET_ID}}">-</span></li>',
  '          <li class="flex justify-between items-start gap-3 min-w-0"><span class="text-zinc-400 flex-shrink-0">Hora:</span><span class="font-semibold text-blue-400 text-right break-words min-w-0" id="summary-time-{{WIDGET_ID}}">-</span></li>',
  '        </ul>',
  '      </div>',
  '      <div class="flex gap-2.5 mt-6"><button id="btn-back-3-{{WIDGET_ID}}" class="w-1/3 py-4 rounded-xl font-bold bg-zinc-800 hover:bg-zinc-700 text-zinc-300 border border-zinc-700/50 transition-colors text-sm">Editar</button><button id="btn-confirm-{{WIDGET_ID}}" class="w-2/3 py-4 rounded-xl font-bold bg-emerald-600 text-white shadow-lg shadow-emerald-600/30 hover:bg-emerald-500 transition-colors flex items-center justify-center gap-2 text-sm"><svg class="w-4 h-4 fill-current" viewBox="0 0 24 24"><path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981zm11.387-5.464c-.074-.124-.272-.198-.57-.347-.297-.149-1.758-.868-2.031-.967-.272-.099-.47-.149-.669.149-.198.297-.768.967-.941 1.165-.173.198-.347.223-.644.074-.297-.149-1.255-.462-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.521.151-.172.2-.296.3-.495.099-.198.05-.372-.025-.521-.075-.148-.669-1.611-.916-2.206-.242-.579-.487-.501-.669-.51l-.57-.01c-.198 0-.52.074-.792.372s-1.04 1.016-1.04 2.479 1.065 2.876 1.213 3.074c.149.198 2.095 3.2 5.076 4.487.709.306 1.263.489 1.694.626.712.226 1.36.194 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.695.248-1.29.173-1.414z"/></svg><span>Confirmar WA</span></button></div>',
  '    </div>',
  '  </div>',
  '  <style>',
  '    .hide-scrollbar::-webkit-scrollbar { display: none; } .hide-scrollbar { -ms-overflow-style: none; scrollbar-width: none; }',
  '    input:-webkit-autofill, input:-webkit-autofill:hover, input:-webkit-autofill:focus { -webkit-text-fill-color: #f4f4f5 !important; -webkit-box-shadow: 0 0 0px 1000px #09090b inset !important; transition: background-color 5000s ease-in-out 0s; }',
  '  </style>',
  '  <script>',
  '    (function() {',
  '      const HOLIDAYS = ["2026-01-01","2026-02-16","2026-02-17","2026-03-24","2026-04-02","2026-04-03","2026-05-01","2026-05-25","2026-06-17","2026-06-20","2026-07-09","2026-08-17","2026-10-12","2026-11-20","2026-12-08","2026-12-25","2027-01-01","2027-02-15","2027-02-16","2027-03-24","2027-04-02"];',
  '      function initWidget(opts = {}) {',
  '        const wId = opts.widgetId || "{{WIDGET_ID}}"; const root = document.getElementById("smart-turnero-widget-" + wId); if (!root) return;',
  '        const parseWorkdays = (str) => (str || "1,2,3,4,5,6").split(",").map(n => parseInt(n.trim(), 10));',
  '        const cfg = {',
  '          open: opts.open || root.dataset.open || "09:00", close: opts.close || root.dataset.close || "13:00", isSplit: opts.isSplit !== undefined ? !!opts.isSplit : (root.dataset.split === "true"),',
  '          open2: opts.open2 || root.dataset.open2 || "17:00", close2: opts.close2 || root.dataset.close2 || "21:00", interval: parseInt(opts.interval || root.dataset.interval || "30", 10), maxDays: parseInt(opts.days || root.dataset.days || "14", 10),',
  '          bizName: opts.bizName || root.dataset.bizName || "{{BUSINESS_NAME}}", waNumber: (opts.wa || root.dataset.wa || "{{WHATSAPP_NUMBER}}").replace(/\\D/g, ""),',
  '          workdays: Array.isArray(opts.workdays) ? opts.workdays : parseWorkdays(opts.workdays || root.dataset.workdays), blockHolidays: opts.blockHolidays !== undefined ? !!opts.blockHolidays : (root.dataset.blockHolidays === "true"),',
  '          holidayExceptions: opts.holidayExceptions || {}, template: opts.template || root.dataset.template || "¡Hola! Quiero confirmar mi reserva en {{comercio}}:\\n- 👤 Nombre: {{cliente}}\\n- 📅 Día: {{fecha}}\\n- ⏰ Hora: {{hora}}\\n- 📞 Tel: {{telefono}}\\n¿Me confirman disponibilidad?"',
  '        };',
  '        const $ = (id) => document.getElementById(id + "-" + wId);',
  '        const dom = { s1: $("step-1"), s2: $("step-2"), s3: $("step-3"), d1: $("step-dot-1"), d2: $("step-dot-2"), d3: $("step-dot-3"), b1: $("step-bar-1"), b2: $("step-bar-2"), sub: $("turnero-subtitle"), bizTitle: $("biz-title"), daySel: $("day-selector"), timeSel: $("time-selector"), dayPrev: $("day-prev"), dayNext: $("day-next"), btnNext1: $("btn-next-1"), btnNext2: $("btn-next-2"), btnBack2: $("btn-back-2"), btnBack3: $("btn-back-3"), btnConfirm: $("btn-confirm"), inpFName: $("input-fname"), inpLName: $("input-lname"), inpPhone: $("input-phone"), err2: $("step-2-error"), sumName: $("summary-name"), sumDay: $("summary-day"), sumTime: $("summary-time") };',
  '        if (!dom.s1 || !dom.btnNext1) return; if (dom.bizTitle) dom.bizTitle.innerText = "Reservar en " + cfg.bizName;',
  '        const state = { step: 1, dayOffset: 0, day: null, dateObj: null, time: null, fname: "", lname: "", phone: "", isToday: false, activeDayData: null };',
  '        const toTitleCase = (str) => (str || "").trim().toLowerCase().replace(/(?:^|\\s|-|\')\\S/g, c => c.toUpperCase());',
  '        const sanitizePhone = (val) => val.replace(/\\D/g, "").replace(/^549?/, "").replace(/^0/, "").replace(/^(\\d{2,4})15/, "$1");',
  '        const validateName = (val) => /^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]{2,30}$/.test((val || "").trim());',
  '        const hasBadWords = (str) => ["mierda","puto","puta","boludo","pelotudo","concha","hdp","spam","carajo","forro"].some(w => (str || "").toLowerCase().includes(w)) || /[<>{}\\\\/]/.test(str);',
  '        try { const saved = JSON.parse(localStorage.getItem("tucu_turnero_profile") || "{}"); if (saved.phone && dom.inpPhone && !dom.inpPhone.value) dom.inpPhone.value = saved.phone; if (saved.fname && dom.inpFName && !dom.inpFName.value) dom.inpFName.value = saved.fname; if (saved.lname && dom.inpLName && !dom.inpLName.value) dom.inpLName.value = saved.lname; } catch(e) {}',
  '        if (dom.inpPhone) {',
  '          dom.inpPhone.addEventListener("input", (e) => { e.target.value = e.target.value.replace(/\\D/g, ""); try { const saved = JSON.parse(localStorage.getItem("tucu_turnero_profile") || "{}"); if (saved.phone && e.target.value === saved.phone) { if (dom.inpFName && !dom.inpFName.value && saved.fname) dom.inpFName.value = saved.fname; if (dom.inpLName && !dom.inpLName.value && saved.lname) dom.inpLName.value = saved.lname; } } catch(err) {} });',
  '          dom.inpPhone.addEventListener("blur", (e) => { e.target.value = sanitizePhone(e.target.value); });',
  '        }',
  '        const toIso = (d) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;',
  '        const getAllDays = () => {',
  '          const days = []; const names = ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"]; let cur = new Date(); let guard = 0; const todayStr = toIso(new Date());',
  '          while (days.length < cfg.maxDays && guard < 120) {',
  '            guard++; const d = new Date(cur); const iso = toIso(d); const isWorkday = cfg.workdays.includes(d.getDay()); const hasEx = cfg.holidayExceptions && cfg.holidayExceptions[iso]; const isHol = cfg.blockHolidays && HOLIDAYS.includes(iso) && !hasEx;',
  '            if (isWorkday && !isHol) days.push({ isToday: iso === todayStr, label: iso === todayStr ? "Hoy" : names[d.getDay()], date: d.getDate(), fullDate: d, iso, special: hasEx || null, fullStr: d.toLocaleDateString("es-ES", { weekday: "long", day: "numeric", month: "long" }) });',
  '            cur.setDate(cur.getDate() + 1);',
  '          }',
  '          return days;',
  '        };',
  '        const allDays = getAllDays();',
  '        const generateRange = (startStr, endStr, interval) => { const slots = []; let current = new Date(`2000-01-01T${startStr}:00`); const end = new Date(`2000-01-01T${endStr}:00`); while (current <= end) { slots.push(current.toLocaleTimeString("es-ES", { hour: "2-digit", minute: "2-digit" })); current.setMinutes(current.getMinutes() + interval); } return slots; };',
  '        const generateTimeSlots = (dayData) => { if (dayData?.special) return generateRange(dayData.special.open, dayData.special.close, cfg.interval); const s1 = generateRange(cfg.open, cfg.close, cfg.interval); return (!cfg.isSplit || !cfg.open2 || !cfg.close2) ? s1 : [...s1, ...generateRange(cfg.open2, cfg.close2, cfg.interval)]; };',
  '        const renderDays = () => {',
  '          const visibleDays = allDays.slice(state.dayOffset, state.dayOffset + 4);',
  '          dom.daySel.innerHTML = visibleDays.map((d, idx) => {',
  '            const actualIdx = state.dayOffset + idx; const isSelected = state.day === d.fullStr;',
  '            return `<button data-idx="${actualIdx}" class="day-btn py-2.5 px-1 flex flex-col items-center justify-center border rounded-2xl transition-all text-center cursor-pointer select-none ${isSelected ? "bg-blue-600 text-white border-blue-500 shadow-lg shadow-blue-600/30 font-bold" : "bg-zinc-800/70 hover:bg-zinc-800 text-zinc-300 border-zinc-700/60"}"><span class="text-[10px] sm:text-[11px] font-medium opacity-80 uppercase tracking-wider">${d.label}</span><span class="font-bold text-base sm:text-lg leading-tight mt-0.5">${d.date}</span></button>`;',
  '          }).join("");',
  '          if (dom.dayPrev) dom.dayPrev.disabled = state.dayOffset === 0; if (dom.dayNext) dom.dayNext.disabled = state.dayOffset + 4 >= allDays.length;',
  '          dom.daySel.querySelectorAll(".day-btn").forEach(btn => {',
  '            btn.addEventListener("click", (e) => {',
  '              const dayData = allDays[parseInt(e.currentTarget.dataset.idx, 10)];',
  '              state.day = dayData.fullStr; state.dateObj = dayData.fullDate; state.isToday = dayData.isToday; state.time = null; state.activeDayData = dayData;',
  '              if (dom.btnNext1) dom.btnNext1.disabled = true; renderDays(); renderTimes();',
  '            });',
  '          });',
  '        };',
  '        if (dom.dayPrev) dom.dayPrev.addEventListener("click", () => { if (state.dayOffset > 0) { state.dayOffset = Math.max(0, state.dayOffset - 4); renderDays(); } });',
  '        if (dom.dayNext) dom.dayNext.addEventListener("click", () => { if (state.dayOffset + 4 < allDays.length) { state.dayOffset = Math.min(allDays.length - 4, state.dayOffset + 4); renderDays(); } });',
  '        const renderTimes = () => {',
  '          const allSlots = generateTimeSlots(state.activeDayData); const now = new Date(); const currentMins = now.getHours() * 60 + now.getMinutes(); let slotsToRender = [];',
  '          if (state.isToday) {',
  '            const pastSlots = []; const upcomingSlots = [];',
  '            allSlots.forEach(t => { const [sh, sm] = t.split(":").map(Number); if ((sh * 60 + sm) <= currentMins) pastSlots.push(t); else upcomingSlots.push(t); });',
  '            slotsToRender = [...pastSlots.slice(-1).map(t => ({ time: t, isPast: true })), ...upcomingSlots.map(t => ({ time: t, isPast: false }))];',
  '          } else { slotsToRender = allSlots.map(t => ({ time: t, isPast: false })); }',
  '          dom.timeSel.innerHTML = slotsToRender.map(s => {',
  '            if (s.isPast) return `<button disabled class="time-btn opacity-25 bg-zinc-900/60 text-zinc-500 line-through cursor-not-allowed pointer-events-none border border-zinc-800/80 font-normal py-2 text-xs sm:text-sm rounded-xl text-center">${s.time}</button>`;',
  '            const isSelected = state.time === s.time;',
  '            return `<button data-time="${s.time}" class="time-btn py-2 text-xs sm:text-sm rounded-xl transition-all text-center font-semibold ${isSelected ? "bg-blue-600 text-white border-blue-500 shadow-md shadow-blue-600/30 font-bold" : "bg-zinc-800/80 hover:bg-blue-600 hover:text-white text-zinc-200 border border-zinc-700/60"}">${s.time}</button>`;',
  '          }).join("");',
  '          dom.timeSel.querySelectorAll(".time-btn:not([disabled])").forEach(btn => {',
  '            btn.addEventListener("click", (e) => {',
  '              dom.timeSel.querySelectorAll(".time-btn:not([disabled])").forEach(b => { b.className = "time-btn py-2 text-xs sm:text-sm rounded-xl transition-all text-center font-semibold bg-zinc-800/80 hover:bg-blue-600 hover:text-white text-zinc-200 border border-zinc-700/60"; });',
  '              e.currentTarget.className = "time-btn py-2 text-xs sm:text-sm rounded-xl transition-all text-center font-bold bg-blue-600 text-white border-blue-500 shadow-md shadow-blue-600/30";',
  '              state.time = e.currentTarget.dataset.time; if (dom.btnNext1) dom.btnNext1.disabled = !(state.day && state.time);',
  '            });',
  '          });',
  '        };',
  '        const goStep = (step) => {',
  '          [dom.s1, dom.s2, dom.s3].forEach(s => { if (s) { s.classList.remove("opacity-100", "translate-x-0", "pointer-events-auto"); s.classList.add("opacity-0", "pointer-events-none"); } });',
  '          const setStepUI = (activeStep, title) => {',
  '            if (dom.sub) dom.sub.innerText = title;',
  '            [dom.d1, dom.d2, dom.d3].forEach((d, idx) => {',
  '              if (idx + 1 === activeStep) d.className = "w-7 h-7 rounded-full bg-blue-600 text-white font-bold text-xs flex items-center justify-center shadow-lg shadow-blue-500/20 ring-4 ring-blue-500/20 transition-all";',
  '              else if (idx + 1 < activeStep) d.className = "w-7 h-7 rounded-full bg-blue-600 text-white font-bold text-xs flex items-center justify-center transition-all";',
  '              else d.className = "w-7 h-7 rounded-full bg-zinc-800 text-zinc-400 font-bold text-xs flex items-center justify-center transition-all";',
  '            });',
  '            if (dom.b1) dom.b1.className = activeStep > 1 ? "h-full bg-blue-600 w-full transition-all duration-300" : "h-full bg-blue-600 w-0 transition-all duration-300";',
  '            if (dom.b2) dom.b2.className = activeStep > 2 ? "h-full bg-blue-600 w-full transition-all duration-300" : "h-full bg-blue-600 w-0 transition-all duration-300";',
  '          };',
  '          if (step === 1) {',
  '            dom.s1.classList.remove("-translate-x-full"); dom.s1.classList.add("translate-x-0", "opacity-100", "pointer-events-auto");',
  '            dom.s2.classList.add("translate-x-full"); dom.s3.classList.add("translate-x-full"); setStepUI(1, "Paso 1: Selecciona fecha y hora");',
  '          } else if (step === 2) {',
  '            dom.s1.classList.add("-translate-x-full"); dom.s2.classList.remove("translate-x-full", "-translate-x-full");',
  '            dom.s2.classList.add("translate-x-0", "opacity-100", "pointer-events-auto"); dom.s3.classList.add("translate-x-full"); setStepUI(2, "Paso 2: Datos para la reserva");',
  '          } else if (step === 3) {',
  '            if (dom.sumName) dom.sumName.innerText = `${state.fname} ${state.lname}`.trim();',
  '            if (dom.sumDay) dom.sumDay.innerText = state.day; if (dom.sumTime) dom.sumTime.innerText = state.time;',
  '            dom.s1.classList.add("-translate-x-full"); dom.s2.classList.add("-translate-x-full");',
  '            dom.s3.classList.remove("translate-x-full"); dom.s3.classList.add("translate-x-0", "opacity-100", "pointer-events-auto"); setStepUI(3, "Paso 3: Confirma tu solicitud");',
  '          }',
  '        };',
  '        if (dom.btnNext1) dom.btnNext1.addEventListener("click", () => goStep(2)); if (dom.btnBack2) dom.btnBack2.addEventListener("click", () => goStep(1));',
  '        if (dom.btnNext2) dom.btnNext2.addEventListener("click", () => {',
  '          state.fname = toTitleCase(dom.inpFName ? dom.inpFName.value : ""); state.lname = toTitleCase(dom.inpLName ? dom.inpLName.value : "");',
  '          if (dom.inpPhone) dom.inpPhone.value = sanitizePhone(dom.inpPhone.value); state.phone = (dom.inpPhone ? dom.inpPhone.value : "").trim();',
  '          const showError = (msg) => { if (dom.err2) { dom.err2.innerText = msg; dom.err2.classList.remove("hidden"); } };',
  '          if (dom.err2) dom.err2.classList.add("hidden");',
  '          if (state.phone.length < 8 || state.phone.length > 15) return showError("Ingresa un número telefónico válido (8 a 15 dígitos).");',
  '          if (!validateName(state.fname)) return showError("El nombre debe tener al menos 2 letras (sin números).");',
  '          if (!validateName(state.lname)) return showError("El apellido debe tener al menos 2 letras (sin números).");',
  '          if (hasBadWords(state.fname) || hasBadWords(state.lname)) return showError("Los campos contienen palabras no permitidas o caracteres inválidos.");',
  '          goStep(3);',
  '        });',
  '        if (dom.btnBack3) dom.btnBack3.addEventListener("click", () => goStep(2));',
  '        if (dom.btnConfirm) dom.btnConfirm.addEventListener("click", () => {',
  '          const clientName = `${state.fname} ${state.lname}`.trim();',
  '          const text = cfg.template.replace(/\\{\\{cliente\\}\\}/g, clientName).replace(/\\{\\{fecha\\}\\}/g, state.day).replace(/\\{\\{hora\\}\\}/g, state.time).replace(/\\{\\{comercio\\}\\}/g, cfg.bizName).replace(/\\{\\{telefono\\}\\}/g, state.phone);',
  '          try { localStorage.setItem("tucu_turnero_profile", JSON.stringify({ phone: state.phone, fname: state.fname, lname: state.lname })); } catch(e) {}',
  '          window.open(`https://wa.me/${cfg.waNumber}?text=${encodeURIComponent(text)}`, "_blank");',
  '        });',
  '        renderDays();',
  '      }',
  '      window.initTurneroL1 = initWidget;',
  '      if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", () => initWidget()); else setTimeout(() => initWidget(), 50);',
  '    })();',
  '  </script>',
  '</div>'
];

fs.writeFileSync(targetPath, lines.join('\n') + '\n', 'utf-8');
const finalCount = fs.readFileSync(targetPath, 'utf-8').split('\n').length;
console.log(`✅ booking_l1_turnero.html escrito con éxito. Total líneas: ${finalCount}`);
